<h2>§6 Widerrufsrecht des Kunden als Verbraucher:</h2>
<p>
    Widerrufsrecht für Verbraucher
    <br/><br/>
    Verbrauchern steht ein Widerrufsrecht nach folgender Maßgabe zu, wobei Verbraucher jede natürliche Person ist, die ein Rechtsgeschäft zu Zwecken abschließt, die überwiegend weder ihrer gewerblichen noch ihrer selbständigen beruflichen Tätigkeit zugerechnet werden können:
    Widerrufsbelehrung
    <br/><br/>
    1. Widerrufsrecht
    Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen. Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag an dem Sie oder
    ein von Ihnen benannter Dritter, der nicht der Beförderer ist, die Ware in Besitz
    genommen haben bzw. hat. Sollte Ihre Bestellung in Teilen geliefert werden, gilt der Tag des Erhalts der letzten Teillieferung. Um Ihr Widerrufsrecht auszuüben, müssen Sie uns, dem Unternehmen: Engelstein UG (haftungsbeschränkt) • Salomonstr. 26-28, 04103 Leipzig (Mail: info@engelstein.de) mittels einer eindeutigen Erklärung (z.B. ein mit der Post versandter Brief oder E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Sie können dafür das beigefügte Muster-Widerrufsformular (s. Anhang 1) verwenden, das jedoch nicht vorgeschrieben ist. Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.
    <br/><br/>
    2. Folgen des Widerrufs
    Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, günstigste Standardlieferung gewählt haben), unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet. Bitte geben Sie bei der Zahlungsart Überweisungen im Rahmen Ihrer Widerrufserklärung Ihre vollständigen Kontodaten ggf. erneut an. Wir können die Rückzahlung verweigern, bis wir die Waren wieder zurückerhalten haben oder bis Sie den Nachweis erbracht haben, dass Sie die Waren zurückgesandt haben. Sie haben die Waren unverzüglich und in jedem Fall spätestens binnen vierzehn Tagen ab dem Tag, an dem Sie uns über den Widerruf dieses Vertrags unterrichten, an  uns: Engelstein UG (haftungsbeschränkt) • Salomonstr. 26-28, 04103 Leipzig zurückzusenden oder zu übergeben. Die Frist ist gewahrt, wenn Sie die Waren vor Ablauf der Frist von vierzehn Tagen absenden. Sie tragen die unmittelbaren Kosten der Rücksendung der Waren. Verwenden Sie die original Versandverpackung. Sie müssen für einen etwaigen Wertverlust der Waren nur aufkommen, wenn dieser Wertverlust auf einen zur Prüfung der Beschaffenheit, Eigenschaften und Funktionsweise der Waren nicht notwendigen Umgang mit ihnen zurückzuführen ist.
    <br/><br/>
    3. Ausschluss des Widerrufsrechts
    Das Widerrufsrecht besteht nicht bei Verträgen zur Lieferung von Waren, die nach Kundenspezifikation angefertigt werden oder eindeutig auf die persönlichen Bedürfnisse zugeschnitten sind. Dies gilt insbesondere für die Auswahl besonderer Lackierungen der Gehäuse. Da diese Produkte nicht vorgefertigt werden können, sondern auf Kundenwunsch hergestellt werden. Die vom Widerrufsrecht ausgeschlossenen Produkte, die speziell nach Kundenspezifikationen gefertigt werden, sind in der Shopauswahl mit der Bezeichnung „individuell*“ gekennzeichnet. Bitte kontaktieren Sie uns bei einem Widerrufswunsch trotzdem. Wir werden uns je nach Fall um eine Kulanzregelung bemühen.
    <br /><br/>
    <a href="public/assets/Widerrufsformular.pdf" target="_blank">Wiederrufsformular als PDF</a>
</p>